#include <stdio.h>
int main()
{
    int a, *ptr=&a;

    scanf("%d", &a);
    printf("%d", *ptr);

    /**PENJELASAN
    [JADI, VARIABEL PTR SAAT DISINI MAKSUDNYA ADALAH DIA AKAN MENGAMBIL/MENYIMPAN SEBUAH NILAI YANG ADA PADA ALAMAT A.
    NANTINYA KETIKA POINTER DIPANGGIL, DIA AKAN MEMILIKI NILAI SESUAI VARIABEL YANG ALAMATNYA DISIMPAN DALAM POINTER]**/
}
